export 'package:gb_shop/Screens/About_Screen.dart';
export 'package:gb_shop/Screens/Cons_POI_Screen.dart';
export 'package:gb_shop/Screens/Home_Screen.dart';
export 'package:gb_shop/Screens/Reporte_Screen.dart';
export 'package:gb_shop/Screens/Registro_Screen.dart';
export 'package:gb_shop/Screens/Login_Screen.dart';
export 'package:gb_shop/Screens/Map_Screen.dart';
export 'package:gb_shop/Screens/Perfil_Screen.dart';
//export 'package:gb_shop/Screens/Depuracion_Screen.dart';